import os.path

from datetime import datetime
from datetime import timedelta

# for now we only use Beijing time to calculate
beijing_local = datetime.utcnow() + timedelta(hours=8)
date_now_str = beijing_local.strftime("%Y%m%d")

pred_length = 100   # wrfout数据个数
target_height = 300      # 固定参数不改动

def gfs_varnames_path(prefix):
    """
    Get GFSwrfout_varnames.xlsx from efs, its path format is like /fsx/domain_1/20230914/post/GFSwrfout_varnames.xlsx
    Please guarantee this file is uploaded to each domain folder like s3://mybucket/input/domain_1/GFSwrfout_varnames.xlsx before computing
    :param prefix: prefix sample: /fsx/domain_1
    :return: GFSwrfout_varnames.xlsx file path
    """
    return f"{prefix}/post/GFSwrfout_varnames.xlsx"


def gfs_database_dir(prefix):
    """
    Get wrf out files path, which are generated by run step, and placed in /fsx/domain_1/run/20230914 path
    These files will place as input files for post-handling, post-handing will combine these files and GFSwrfout_varnames.xlsx
    then output compressed wrfout files
    :param prefix: /fsx/domain_1
    :return:
    """
    return f"{prefix}/run"


def gfs_cut_database_dir(prefix):
    """
    Get compressed(cut) wrf out file path
    :param prefix: /fsx/domain_1
    :return: compressed wrf out file path
    """
    return f"{prefix}/post/gfs_cut"


def locat_path(prefix):
    """
    Get location files path
    Post-handing will use this file and compressed(cut) wrf out files to generate Excel and NetCDF files
    :param prefix: /fsx/domain_1
    :return:
    """
    return f"{prefix}/post/locations.xlsx"

def gfs_excel_database_dir(prefix):
    """
    Get gfs Excel file path
    Post-handing process will combine cut wrf out files and location file then produce Excel files and NetCDF files
    About location file please refer to `locat_path`
    :param prefix: /fsx/domain_1/post
    :return: compressed wrf out file path
    """
    return f"{prefix}/post/gfs_excel"


def gfs_netcdf_dir(prefix):
    """
    Get gfs Excel file path
    Post-handing process will combine cut wrf out files and location file then produce Excel files and NetCDF files
    About location file please refer to `locat_path`
    :param prefix: sample /fsx/domain_1/post
    :return: compressed wrf out file path
    """
    return f"{prefix}/post/gfs_netcdf"


def gfs_log_path(prefix):
    return f"{prefix}/post/logs/gfs_{date_now_str}.log"


def record_dir(prefix):
    return f"{prefix}/post/record"




