import os.path
import time

date_now_str = time.strftime('%Y%m%d', time.localtime())

pred_length = 100   # wrfout数据个数
target_height = 300      # 固定参数不改动
# $jobdir/$i/post add domain parameter
# --database
# --log
# gfs_database_dir should be $jobdir/$i/run

# gfs_varnames_path = "/hpc/stage/zhaozz/code/python/short_prepare_domains/static_data/GFSwrfout_varnames.xlsx"   # 指定输入的变量信息文件（用我发的就好）
# gfs_database_dir = "/hpc/stage/zhaozz/code/python/short_prepare_operation/database/gfs"   #  wrfout路径，wrfout必须存放在这个路径下的日前文件夹中，例如gfs_database_dir+"/20230906/"
# gfs_cut_database_dir = "/hpc/stage/zhaozz/code/python/short_prepare_domains/xiyang1/database/gfs_cut"   # 第一种结果路径：压缩后的wrfout
# gfs_excel_database_dir = "/hpc/stage/zhaozz/code/python/short_prepare_domains/xiyang1/database/gfs_excel"   # 第二种结果路径：Excel文件
# gfs_netcdf_dir = "/hpc/stage/zhaozz/code/python/short_prepare_domains/xiyang1/database/gfs_netcdf"   #  第三种结果路径：nc格式文件
# gfs_log_path = f"/hpc/stage/zhaozz/code/python/short_prepare_domains/xiyang1/log/gfs_{date_now_str}.log"    # log路径
# locat_path = "/hpc/stage/zhaozz/code/python/short_prepare_domains/static_data/location_xiyang1.xlsx"   # 指定输入的目标位置信息文件（用我发的就好）
# record_dir = "/hpc/stage/zhaozz/code/python/short_prepare_domains/xiyang1/record"   # 指定输出第二种log文件路径

def gfs_varnames_path(prefix):
    """
    Get GFSwrfout_varnames.xlsx from efs, its path format is like /fsx/domain_1/20230914/post/GFSwrfout_varnames.xlsx
    Please guarantee this file is uploaded to each domain folder like s3://mybucket/input/domain_1/GFSwrfout_varnames.xlsx before computing
    :param prefix: prefix sample: /fsx/domain_1
    :return: GFSwrfout_varnames.xlsx file path
    """
    return f"{prefix}/post/GFSwrfout_varnames.xlsx"

def gfs_database_dir(prefix):
    """
    Get wrf out files path, which are generated by run step, and placed in /fsx/domain_1/run/20230914 path
    These files will place as input files for post-handling, post-handing will combine these files and GFSwrfout_varnames.xlsx
    then output compressed wrfout files
    :param prefix: /fsx/domain_1
    :return:
    """
    return f"{prefix}/run/{date_now_str}"

def gfs_cut_database_dir(prefix):
    """
    Get compressed(cut) wrf out file path
    :param prefix: /fsx/domain_1
    :return: compressed wrf out file path
    """
    return f"{prefix}/post/gfs_cut"

def locat_path(prefix):
    """
    Get location files path
    Post-handing will use this file and compressed(cut) wrf out files to generate Excel and NetCDF files
    :param prefix: /fsx/domain_1
    :return:
    """
    return f"{prefix}/post/locations.xlsx"

def gfs_excel_database_dir(prefix):
    """
    Get gfs Excel file path
    Post-handing process will combine cut wrf out files and location file then produce Excel files and NetCDF files
    About location file please refer to `locat_path`
    :param prefix: /fsx/domain_1/post
    :return: compressed wrf out file path
    """
    return f"{prefix}/post/gfs_excel"

def gfs_netcdf_dir(prefix):
    """
    Get gfs Excel file path
    Post-handing process will combine cut wrf out files and location file then produce Excel files and NetCDF files
    About location file please refer to `locat_path`
    :param prefix: sample /fsx/domain_1/post
    :return: compressed wrf out file path
    """
    return f"{prefix}/post/gfs_netcdf"

def gfs_log_path(prefix):
    return f"{prefix}/post/log/gfs_{date_now_str}.log"

def record_dir(prefix):
    return f"{prefix}/post/record"




